import type { CopilotDraft, InboxThread } from '@shared/types'
import { extractEmail } from '@/lib/inbox/extractEmail'

export async function generateDraftForThread(
  thread: InboxThread,
  toneTier = 'peer',
  onToken?: (text: string) => void,
): Promise<string> {
  const res = await fetch('/api/claude/draft-reply', {
    method: 'POST',
    credentials: 'include',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: {
        from: thread.from,
        fromEmail: extractEmail(thread.from, thread.fromDomain),
        subject: thread.subject,
        snippet: thread.snippet,
      },
      toneTier,
    }),
  })
  if (!res.ok || !res.body) throw new Error('Draft generation failed')

  const reader = res.body.getReader()
  const decoder = new TextDecoder()
  let accumulated = ''
  let buffer = ''
  let sawTerminal = false // saw a `done` or `error` event

  const handleLine = (line: string) => {
    if (!line.startsWith('data: ')) return
    let parsed: { type?: string; text?: string; draft?: string; message?: string }
    try {
      parsed = JSON.parse(line.slice(6))
    } catch {
      return
    }
    if (!parsed || typeof parsed !== 'object') return
    if (parsed.type === 'token') {
      accumulated += parsed.text ?? ''
      if (parsed.text) onToken?.(parsed.text)
    } else if (parsed.type === 'done') {
      if (typeof parsed.draft === 'string') accumulated = parsed.draft
      sawTerminal = true
    } else if (parsed.type === 'error') {
      throw new Error(parsed.message || 'Draft generation failed')
    }
  }

  while (true) {
    const { done, value } = await reader.read()
    if (done) break
    buffer += decoder.decode(value, { stream: true })
    const lines = buffer.split('\n')
    buffer = lines.pop() ?? ''
    for (const line of lines) handleLine(line)
  }
  // Flush a trailing line left without a terminating newline, then require a
  // terminal event so a truncated stream surfaces as an error instead of a
  // silently-partial "success" (mirrors src/lib/briefStream.ts).
  if (buffer.trim()) handleLine(buffer)
  if (!sawTerminal) throw new Error('Draft stream ended before completion')
  return accumulated
}

// Cache-read for the deck (Task 14): drafts pre-generated by the inbox scan
// (Task 11/12) and cached server-side (Task 13). A non-ok response or an
// unparsable body degrades to "no cache" rather than throwing, so a hiccup
// here never blocks the on-demand draft path in useCopilotStore.
export async function fetchCachedDrafts(): Promise<Record<string, CopilotDraft>> {
  const res = await fetch('/api/copilot/drafts', { credentials: 'include' })
  if (!res.ok) return {}
  const json = await res.json().catch(() => ({ data: {} }))
  return (json.data ?? {}) as Record<string, CopilotDraft>
}
